name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies 
        run: |
          pip install .
          pip install coverage
      - name: unittest
        run:
          coverage run -m unittest tests/unit_test.py 
          coverage report
